### ISSUE TITLE
Use libraries with same version as powsybl-core 

### ISSUE THREAD

**Issue by flo-dup** [powsybl/powsybl-entsoe#20]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
2 libraries are used with a more recent version than powsybl-core one:
   - threeten-extra (1.5.0 instead of 1.0.0)
   - jackson-annotations (2.11.2 instead of 2.10.5)

* **What is the expected behavior?**
Same version used as in powsybl-core

* **What is the motivation / use case for changing the behavior?**
Use only one version for libraries across the whole powsybl repositories

**Comment by miovd** [comment]
Fixed by #25
