### ISSUE TITLE
[Flow decomposition] Handle post contingencies calculation

### ISSUE THREAD

**Issue by murgeyseb** [powsybl/powsybl-entsoe#71]
* **Do you want to request a *feature* or report a *bug*?**
New feature

* **What is the current behavior?**
Current implementation of flow decomposition algorithm only handles calculation on the initial state of the network.

* **What is the expected behavior?**
Flow decomposition should allow to specify XNE to be analysed both in initial state, and on post contingency states.

* **What is the motivation / use case for changing the behavior?**
Alignment with business requirements for the flow decomposition algorithm

**Comment by OpenSuze** [comment]
#74

**Comment by OpenSuze** [comment]
#76
